#source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Eyshen/ios-zy-framework-cocoapods-specs.git'


platform :ios, '8.0'

inhibit_all_warnings!

target 'ios-zy-hulk' do

pod 'QMUIKit'
    
pod 'ZYConfig'

pod 'ZYJSON'

pod 'ZYLoggingAPI'

pod 'MJRefresh'

pod 'Masonry'

pod 'FMDB'

pod 'ZYLoggingCocoaLumberjack'

#pod 'ReactiveCocoa', '=2.3'

#pod 'ZYCrashProtector', '0.1.3'

#pod 'YTKNetwork'

#pod 'AvoidCrash'

#组件库
#pod 'WJNetworkContextService'

#pod 'WJAppContext'

#pod 'WJDeviceID'

#pod 'WJPlayerKit'

#pod 'WJPlayerCacheVI'

#pod 'WJHttpEngineAF'

#pod 'WJCacheAPI'

#pod 'WJHttpEngineAPI'

#pod 'WJRouter'

#pod 'WJCacheKeychain'

#pod 'WJHttpServiceAF'

#pod 'WJSession'

#pod 'WJCacheUserDefaults'

#pod 'WJHttpServiceAPI'

#pod 'WJUIRoutable'

#pod 'WJCommon'

#pod 'WJJSON'

#pod 'WJWebViewJavascriptBridge'

#pod 'WJConfig'

#pod 'WJLoggingAPI'

#pod 'WJCoreDataDA'

#pod 'WJNetworkContextService'

end
