source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Eyshen/ios-zy-framework-cocoapods-specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

target 'ios-zy-hulk' do

pod 'QMUIKit' , '2.9.3'
    
pod 'ZYConfig'

pod 'ZYJSON'

end
